theme: minima
title: Enterprise Internals
description: "How Enterprise Systems, Cloud, and Strategy Actually Work in Practice"
sass:
  style: compressed
  
header_pages:
  - index.md
  - about.md
  - contact.md
  - blogs.md
