theme: minima
title: Lucid Stack
description: "Breaking Down Enterprise Cloud, Platforms, and Automation"
sass:
  style: compressed
  
header_pages:
  - index.md
  - about.md
  - contact.md
  - blogs.md
